import io
import re
import os
from datetime import datetime
from fpdf import FPDF

FONT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'fonts')


class GoldReportPDF(FPDF):
    def __init__(self):
        super().__init__()
        font_regular = os.path.join(FONT_DIR, 'Sarabun-Regular.ttf')
        font_bold = os.path.join(FONT_DIR, 'Sarabun-Bold.ttf')

        if os.path.exists(font_regular):
            self.add_font('Sarabun', '', font_regular, uni=True)
        if os.path.exists(font_bold):
            self.add_font('Sarabun', 'B', font_bold, uni=True)

        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        # Dark header background
        self.set_fill_color(25, 25, 30)
        self.rect(0, 0, 210, 38, 'F')

        # Gold accent line
        self.set_fill_color(212, 175, 55)
        self.rect(0, 38, 210, 1.5, 'F')

        # Title
        self.set_font('Sarabun', 'B', 20)
        self.set_text_color(212, 175, 55)
        self.set_y(8)
        self.cell(0, 12, 'Gold Options Analysis Report', 0, 1, 'C')

        # Subtitle
        self.set_font('Sarabun', '', 10)
        self.set_text_color(160, 160, 170)
        self.cell(0, 7, 'CME QuikStrike  |  Institutional Grade Analysis', 0, 1, 'C')

        self.ln(8)

    def footer(self):
        self.set_y(-22)
        self.set_draw_color(212, 175, 55)
        self.set_line_width(0.3)
        self.line(15, self.get_y(), 195, self.get_y())
        self.ln(3)
        self.set_font('Sarabun', '', 7)
        self.set_text_color(130, 130, 130)
        self.cell(0, 5, f'Generated by Gold Options Bot  |  Page {self.page_no()}/{{nb}}', 0, 1, 'C')
        self.cell(0, 4, 'For informational purposes only. Not financial advice.', 0, 0, 'C')

    def section_header(self, title):
        """Draw a styled section header"""
        self.ln(4)
        # Gold left bar
        y = self.get_y()
        self.set_fill_color(212, 175, 55)
        self.rect(10, y, 3, 8, 'F')
        # Title text
        self.set_font('Sarabun', 'B', 13)
        self.set_text_color(30, 30, 35)
        self.set_x(16)
        self.cell(0, 8, title, 0, 1)
        # Thin line under
        self.set_draw_color(220, 220, 220)
        self.set_line_width(0.2)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)

    def body_text(self, text):
        """Add body text"""
        self.set_font('Sarabun', '', 10)
        self.set_text_color(50, 50, 55)
        wrapped_text = wrap_thai_text(self, text, 155)
        self.multi_cell(0, 5.5, wrapped_text)

    def bullet_text(self, text):
        """Add indented bullet text"""
        self.set_font('Sarabun', '', 10)
        self.set_text_color(60, 60, 65)
        self.set_x(15)
        wrapped_text = wrap_thai_text(self, text, 175)
        self.multi_cell(180, 5.5, wrapped_text)

def wrap_thai_text(pdf, text, max_width):
    """Manually wrap text to max_width to prevent FPDF2 crash with long Thai strings"""
    result = ""
    current_line = ""
    for char in text:
        if char == '\n':
            result += current_line + char
            current_line = ""
            continue
            
        is_combining = ('\u0E31' <= char <= '\u0E3A') or ('\u0E47' <= char <= '\u0E4E')
        if not is_combining and current_line and pdf.get_string_width(current_line + char) > max_width:
            result += current_line + '\n'
            current_line = char
        else:
            current_line += char
    result += current_line
    return result



def strip_emoji(text):
    """Remove emoji characters for cleaner PDF"""
    emoji_pattern = re.compile(
        "["
        "\U0001F000-\U0001F9FF"
        "\U0001FA00-\U0001FAFF"
        "\U00002600-\U000026FF"
        "\U00002700-\U000027BF"
        "\U0001F1E0-\U0001F1FF"
        "\uFE00-\uFE0F"
        "\u2000-\u2BFF"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub('', text)


def clean_markdown(text):
    """Convert markdown to clean text for PDF"""
    text = strip_emoji(text)
    text = re.sub(r'\*\*\*(.*?)\*\*\*', r'\1', text)
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    text = re.sub(r'```[\s\S]*?```', '', text)
    text = re.sub(r'`(.*?)`', r'\1', text)
    text = re.sub(r'^#{1,6}\s+', '', text, flags=re.MULTILINE)
    text = re.sub(r'^---+$', '', text, flags=re.MULTILINE)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()


# Section header emoji/keywords to detect
SECTION_KEYWORDS = [
    'Snapshot', 'Expected Range', 'Key Levels', 'Z-Score',
    'Volume', 'Heatmap', 'Volatility', 'Greeks',
    'Anomaly', 'Bias', 'CFD', 'Long', 'Short', 'Hedging',
    'สรุป', 'แนะนำ', 'สัญญาณ', 'กลยุทธ์'
]


def is_section_header(line):
    """Check if a line looks like a section header"""
    stripped = line.strip()
    if not stripped:
        return False
    for kw in SECTION_KEYWORDS:
        if kw in stripped:
            if len(stripped) < 80:
                return True
    return False


def generate_pdf(result_text, timestamp=None):
    """Generate a premium PDF report from analysis result text.
    Returns bytes of the PDF file."""
    if timestamp is None:
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    pdf = GoldReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    # Date stamp
    pdf.set_font('Sarabun', '', 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, f'Analysis Date: {timestamp}', 0, 1, 'R')
    pdf.ln(3)

    # Process content
    cleaned = clean_markdown(result_text)
    lines = cleaned.split('\n')

    for line in lines:
        line = line.rstrip()

        if not line:
            pdf.ln(2)
            continue

        # Table rows
        if '|' in line and line.strip().startswith('|'):
            cells = [c.strip() for c in line.split('|') if c.strip()]
            # Skip separator rows (|---|---|)
            if cells and all(c.replace('-', '').replace(':', '').strip() == '' for c in cells):
                continue
            if cells:
                pdf.set_font('Sarabun', '', 8)
                pdf.set_text_color(40, 40, 45)
                col_w = 185 / max(len(cells), 1)
                pdf.set_x(12)
                for cell_text in cells:
                    pdf.cell(col_w, 6, cell_text[:35], 1, 0, 'C')
                pdf.ln()
            continue

        # Section headers
        if is_section_header(line):
            pdf.section_header(line.strip())
            continue

        # Bullet points
        if line.strip().startswith(('-', '•')):
            pdf.bullet_text(line.strip())
            continue

        # Regular text
        pdf.body_text(line)

    return bytes(pdf.output())
